FROM nginx:alpine

# Salin konfigurasi Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Salin file static
COPY ./templates/ /usr/share/nginx/html/
COPY ./static/ /usr/share/nginx/html/static/

# Fix permission
RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 5000