apiVersion: v1
kind: Service
metadata:
  name: cracker-service
spec:
  type: NodePort
  selector:
    app: cracker
  ports:
  - name: frontend
    port: 5000
    targetPort: 5000
    nodePort: 30000
  - name: backend
    port: 5001
    targetPort: 5001
    nodePort: 30001
  - name: redis
    port: 6379
    targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: worker-service
spec:
  type: ClusterIP  # Ditambahkan untuk kejelasan
  selector:
    app: worker
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80