apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cracker-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard