FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y hashcat python3 python3-pip redis-tools vim && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY worker.py .

RUN python3 -m pip install --no-cache-dir redis

# Pastikan /data writable
RUN mkdir -p /data && chmod -R 777 /data

CMD ["python3", "-u", "worker.py"]